SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE `__referrals` ADD `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' AFTER `id`, ADD INDEX (`user_id`);

COMMIT;
