SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE `__users` ADD `birthday` DATE NULL DEFAULT NULL AFTER `address`;
ALTER TABLE `__users` ADD INDEX(`birthday`);

COMMIT;
