SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE `sfly_referrals` ADD `value_referrer` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT '0.00' AFTER `value`;

COMMIT;
