SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE `sfly_products` ADD `bonuses` DECIMAL(14,2) UNSIGNED NOT NULL DEFAULT '0.00';

COMMIT;
