{* Order page *}

{* The page title *}
{$meta_title = "`$lang->email_order_title` `$order->id`" scope=parent}

{* The page heading *}
<div class="order_notify_v2">
    <div class="o_notify_v2_head">
        {include file="svg.tpl" svgId="success_icon"}
        <span class="o_notify_v2_heading">{$lang->order_greeting} <span data-language="order_success_issued">{$lang->order_success_issued}</span></span>
         {* <span class="o_notify_v2_order_id_bold">№ {$order->id}</span>  *}
    </div>
    <div class="o_notify_v2_content">
        <div class="o_notify_v2_content_inner" data-language="order_success_text">
            <p><strong>{$order->name|escape}</strong>, {$lang->order_success_text}</p>
            {*Payment form is generated by payment module*}
            {*payment's form HTML code is in the /payment/ModuleName/form.tpl*}
            {checkout_form order_id=$order->id module=$payment_method->module}
        </div>
    </div>
</div>

<div class="order_wrapper">
    <div class="col-lg-6 no_padding order_left_wrapper">
        <div class="h2">
            <span data-language="order_details">{$lang->order_details} <span>№ {$order->id}</span></span>
        </div>
        {* Order details *}
        <div class="padding">
            <table class="order_details">
                <tr>
                    <td>
                        <span data-language="user_order_status">{$lang->user_order_status}</span>
                    </td>
                    <td>
                        {$order_status->name|escape}
                        {if $order->paid == 1}
                            , <span data-language="status_paid">{$lang->status_paid}</span>
                        {/if}
                    </td>
                </tr>
                <tr>
                    <td>
                        <span data-language="order_date">{$lang->order_date}</span>
                    </td>
                    <td>{$order->date|date} <span data-language="order_time">{$lang->order_time}</span> {$order->date|time}</td>
                </tr>
                <tr>
                    <td>
                        <span data-language="order_name">{$lang->order_name}</span>
                    </td>
                    <td>{$order->name|escape}</td>
                </tr>
                <tr>
                    <td>
                        <span data-language="order_email">{$lang->order_email}</span>
                    </td>
                    <td>{$order->email|escape}</td>
                </tr>
                {if $order->phone}
                    <tr>
                        <td>
                            <span data-language="order_phone">{$lang->order_phone}</span>
                        </td>
                        <td>{$order->phone|escape}</td>
                    </tr>
                {/if}
                {if $order->address}
                    <tr>
                        <td>
                            <span data-language="order_address">{$lang->order_address}</span>
                        </td>
                        <td>{$order->address|escape}</td>
                    </tr>
                {/if}
                {if $order->comment}
                    <tr>
                        <td>
                            <span data-language="order_comment">{$lang->order_comment}</span>
                        </td>
                        <td>{$order->comment|escape|nl2br}</td>
                    </tr>
                {/if}
                {if $delivery}
                    <tr>
                        <td>
                            <span data-language="order_delivery">{$lang->order_delivery}</span>
                        </td>
                        <td>{$delivery->name|escape}</td>
                    </tr>
                {/if}
            </table>
        </div>
    </div>

    <div class="col-lg-6 no_padding order_right_wrapper">
        {if !$order->paid && !$order->advance_paid}
            {* Payments *}
            <div class="h2">
                <span data-language="order_payment_details">{$lang->order_payment_details}</span>
            </div>

            {if $payment_methods && !$payment_method && $order->total_price>0}
                <div class="delivery padding">
                    <form method="post">
                       {*  {foreach $payment_methods as $payment_method}
                            <div class="delivery_item">
                                <label class="delivery_label{if $payment_method@first} active{/if}">
                                    <i class="filter_indicator"></i>
                                    <input class="input_delivery"  type="radio" name="payment_method_id" value="{$payment_method->id}" {if $delivery@first && $payment_method@first} checked{/if} id="payment_{$delivery->id}_{$payment_method->id}">
                                    <span class="delivery_name">
                                        {$total_price_with_delivery = $cart->total_price}
                                        {if !$delivery->separate_payment && $cart->total_price < $delivery->free_from}
                                            {$total_price_with_delivery = $cart->total_price + $delivery->price}
                                        {/if}
                                    
                                        {$payment_method->name|escape}
                                        {if $order->total_advance}
                                            ({$lang->payment_info_advance}
                                            {$order->total_advance|convert}
                                            {$currency->sign|escape})
                                        {/if}
                                        {$lang->cart_deliveries_to_pay}
                                        <span class="nowrap">{$order->total_price|convert:$payment_method->currency_id} {$all_currencies[$payment_method->currency_id]->sign}</span>
                                    </span>
                                </label>
                                <div class="delivery_description">
                                    {$payment_method->description}
                                </div>
                            </div>
                        {/foreach} *}

                        <div class="cart_step_2_right_wrapper ">
                            {include file='order_purchases.tpl'}
                            {* Discount *}
                            {if $user->discount}
                                <div class="cart_coupon_percent_wrapper">
                                    <div class="text_left" data-language="cart_discount">{$lang->cart_discount}</div>
                                    <div>{$order->discount}%</div>
                                </div>
                            {/if}

                            {* Coupon *}
                            {if $order->coupon_discount > 0}
                                <div class="cart_coupon_percent_wrapper">
                                    <div class="text_left" data-language="cart_coupon">{$lang->cart_coupon} <span class="cart_coupon_percent">{$cart->coupon->coupon_percent|escape} %</span></div>
                                    <div>{$order->coupon_discount|convert} {$currency->sign|escape}</div>
                                </div>
                            {/if}
                            <div class="purchase_total">
                                <span data-language="cart_total_price">{$lang->cart_total_price}:</span>
                                <span class="total_sum nowrap">{$order->total_price|convert} {$currency->sign|escape}</span>
                            </div>
                        </div>
                        {* <input type="submit" data-language="cart_checkout" value="{$lang->cart_checkout}" name="checkout" class="button btn_black"> *}
                    </form>
                </div>
            {elseif $payment_method}
                {* Selected payment *}
                <div class="padding payment_method_wrapper clearfix">
                    <div class="method">
                        <div class="method_order_payment_tr">
                            <span class="method_order_payment" data-language="order_payment">{$lang->order_payment}: </span>
                            <span class="method_name">
                                {$payment_method->name|escape}
                                {if $order->total_advance}
                                    ({$lang->payment_info_advance}
                                    {$order->total_advance|convert}
                                    {$currency->sign|escape})
                                {/if}
                            </span>
                        </div>
                        <div class="cart_step_2_right_wrapper 2">
                            {include file='order_purchases.tpl'}
                            {* Discount *}
                            {if $order->discount > 0}
                                <div class="cart_coupon_percent_wrapper">
                                    <div class="text_left" data-language="cart_discount">{$lang->cart_discount}</div>
                                    <div>{$order->discount}%</div>
                                </div>
                            {/if}

                            {* Coupon *}
                            {if $order->coupon_discount > 0}
                                <div class="cart_coupon_percent_wrapper">
                                    <div class="text_left" data-language="cart_coupon">{$lang->cart_coupon} <span class="cart_coupon_percent">{$order->coupon->coupon_percent|escape} %</span></div>
                                    <div>{$order->coupon_discount|convert} {$currency->sign|escape}</div>
                                </div>
                            {/if}
                            <div class="purchase_total">
                                <span data-language="cart_total_price">{$lang->cart_total_price}:</span>
                                <span class="total_sum nowrap">{$order->total_price|convert} {$currency->sign|escape}</span>
                            </div>
                        </div>

                        <div class="method_form_buttons">
                            <form class="method_form" method="post">
                                <input class="button btn_black" type=submit name='reset_payment_method' data-language="order_change_payment" value='{$lang->order_change_payment}'/>
                            </form>
                            {*Payment form is generated by payment module*}
                            {*payment's form HTML code is in the /payment/ModuleName/form.tpl*}
                            {checkout_form order_id=$order->id module=$payment_method->module}
                        </div>

                        {* {if $payment_method->description}
                            <div class="method_description">
                                {$payment_method->description}
                            </div>
                        {/if} *}
                    </div>

                    
                </div>                
            {/if}
        {/if}
    </div>
</div>

{if !$order->ga_ecommerce_sended}
    {literal}
        <script>
            ga('require', 'ecommerce');
            ga('ecommerce:addTransaction', {
                'id': '{/literal}{$order->id}{literal}',
                'affiliation': '{/literal}{$config->root_host}{literal}',
                'revenue': '{/literal}{$order->total_price}{literal}',
                'shipping': '{/literal}{$order->delivery_price}{literal}',
                'currency': '{/literal}{$currency->code|escape}{literal}'
            });
            {/literal}{foreach $purchases as $p}{literal}
            ga('ecommerce:addItem', {
                {/literal}
                'id': '{$order->id}',
                'name': '{$p->product_name|escape}',
                'sku': '{if !empty($p->sku)}{$p->sku|escape}{else}id:{$p->id}{/if}',
                'price': '{$p->price}',
                'quantity': '{$p->amount}'
                {literal}
            });
            {/literal}{/foreach}{literal}
            ga('ecommerce:send');
        </script>
    {/literal}
    {ga_ecommerce_sended orderId = $order->id}
{/if}
{if $smarty.session.order_id && $smarty.session.order_id == $order->id && (($smarty.now - $order->date|strtotime) < 30)}
    {literal}
        <script>
            if (window.localStorage.getItem('lastOrderId') !== '{/literal}{$order->id}{literal}') {
                window.dataLayer = window.dataLayer || [];
                window.dataLayer.push({ ecommerce: null });
                window.dataLayer.push({
                    'event': 'purchase',
                    'ecommerce': {
                        'transaction_id': '{/literal}{$order->id}{literal}',
                        'value': {/literal}{$order->total_price|convert:null:false}{literal},
                        'currency': '{/literal}{$currency->code}{literal}',
                        'shipping': {/literal}{$order->delivery_price|convert:null:false}{literal},
                        'coupon': '{/literal}{$order->coupon_code|escape}{literal}',
                        'items': [
                            {/literal}{foreach $purchases as $purchase}{literal}
                            {
                                'item_name': '{/literal}{$purchase->product->name|escape}{literal}',     
                                'item_id': '{/literal}{$purchase->variant->sku|escape}{literal}',
                                'price': '{/literal}{$purchase->price|convert:null:false}{literal}',
                                'item_brand': '{/literal}{if $purchase->product->brand}{$purchase->product->brand->name|escape}{/if}{literal}',
                                'item_category': '{/literal}{if $purchase->product->category && $purchase->product->category->path[0]}{$purchase->product->category->path[0]->name|escape}{/if}{literal}',
                                'item_category2': '{/literal}{if $purchase->product->category && $purchase->product->category->path[1]}{$purchase->product->category->path[1]->name|escape}{/if}{literal}',
                                'item_category3': '{/literal}{if $purchase->product->category && $purchase->product->category->path[2]}{$purchase->product->category->path[2]->name|escape}{/if}{literal}',
                                'item_category4': '{/literal}{if $purchase->product->category && $purchase->product->category->path[3]}{$purchase->product->category->path[3]->name|escape}{/if}{literal}',
                                'item_variant': '{/literal}{$purchase->variant->name|escape}{literal}',
                                'quantity': '{/literal}{$purchase->amount}{literal}',
                                'discount': '{/literal}{$purchase->amount * ($purchase->price * (1-(100-$order->discount)/100) + (($purchase->price * ((100-$order->discount)/100)) * (($order->paid_bonuses + $order->coupon_discount) / ($order->total_price + $order->paid_bonuses + $order->coupon_discount - ($order->delivery_price * (1-$order->separate_delivery)) ))))}{literal}',
                                'coupon': '{/literal}{$order->coupon_code|escape}{literal}'
    
                            }{/literal}{if !$purchase@last}, {/if}{literal}
                            {/literal}{/foreach}{literal}
                        ]
                    }
                });
                window.localStorage.setItem('lastOrderId', '{/literal}{$order->id}{literal}');
            }
        </script>
    {/literal}
{/if}
{if !$order->paid && !$order->advance_paid}
{literal}
    <script>
        $(()=>{
            if ($('.o_notify_v2_content_inner form')) {
                setTimeout(() => {
                    $('.o_notify_v2_content_inner form').trigger( "submit" );
                }, 1000);
            }
        });
    </script>
{/literal}
{/if}

